
development:
  adapter: postgresql
  encoding: unicode
  database: cats_cuties_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cats_cuties_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: cats_cuties_production
  pool: 5

